[package]
name = "ncc"
version = "1.0.3.30"

[build]
src = "src/01main.nc"
sources = "src/01main.nc src/02transpile.nc src/03output_code.nc src/04heap.nc src/05parse.nc src/06type.nc src/07function.nc src/08call.nc src/09pre_op.nc src/10str.nc src/11number.nc src/12var.nc src/13gvar.nc src/14if.nc src/15while.nc src/16for.nc src/17do_while.nc src/18switch.nc src/19struct.nc src/20union.nc src/21enum.nc src/22typedef.nc src/23field.nc src/24method.nc src/25obj.nc src/26eq.nc src/27impl.nc src/28interface.nc src/29module.nc src/30op.nc src/31type2.nc src/32function2.nc src/33output_code2.nc src/34heap2.nc src/35call2.nc src/36str2.nc src/37var2.nc src/38struct2.nc src/39method2.nc src/40obj2.nc src/41module2.nc src/42op2.nc src/43function3.nc src/44function4.nc src/45function5.nc src/46function6.nc src/47function7.nc src/48function8.nc src/49call3.nc src/50call4.nc src/51str3.nc src/52obj3.nc src/53obj4.nc src/ccpp.nc src/neo-c-str.nc"
out = "target/debug/ncc"
neoc = "./neo-c"
neoc_flags = "-I."
ldflags = "-lutil -ldl -lm -lrt"
common_header = false
strip = true
