#ifndef CPM_COMMON_H
#define CPM_COMMON_H

#include <neo-c.h>

// This file is generated by cpm build from src/*.nc.
// Put manual shared declarations in a separate header and include it from source files.

struct sCommand { list<string>*% args; bool mix_stdout; tuple2<string,bool>*% redirect_stdout; tuple2<string,bool>*% redirect_stderr; };
struct sInfo { char* p; int rcode; list<sCommand*%>*% commands; };
sCommand*% sCommand*::initialize(sCommand*% self);
void skip_spaces(sInfo* info);
void parse_redirect(sInfo* info);
string parse_word(sInfo* info);
int parse_cmp(const char* str, const char* str2);
string expand_env(string value);
bool parse_statment(sInfo* info);
bool redirect(int n, sInfo* info);
bool run_command(int n, sInfo* info);
int, bool run(char* source);
void sig_int(int signal);
void set_signal();
string line_buffer_from_head_to_cursor_point();
void get_command_completion_cadidates();
char* completion_generator(const char* text, int state);
void zed_get_command_completion_cadidates();
char* zed_completion_generator(const char* text, int state);
char** completer(const char* text, int start, int end);
void readline_insert_text(char* cmdline, int cursor_point);
int readline_init_text();

#endif
