#ifndef CPM_COMMON_H
#define CPM_COMMON_H

#include <neo-c.h>

// This file is generated by cpm build from src/*.nc.
// Put manual shared declarations in a separate header and include it from source files.

string fin();

#endif
