#ifndef CPM_COMMON_H
#define CPM_COMMON_H

#include <neo-c.h>

// This file is generated by cpm build from src/*.nc.
// Put manual shared declarations in a separate header and include it from source files.

struct sInfo { int cursor; int page; string path; bool app_end; bool virtual_dir; list<string>*% files; list<string>*% selected_files; string searching_str; };
int xgetmaxx();
int xgetmaxy();
void read_dir(sInfo* info);
void vd(sInfo* info);
bool change_directory(sInfo* info, char* path, char* cursor_file);
void fix_cursor(sInfo* info);
void view(sInfo* info);
string cursor_path(sInfo* info);
string cursor_file(sInfo* info);
string selected_files(sInfo* info);
void search_file(sInfo* info);
void search_next_file(sInfo* info);
void search_prev_file(sInfo* info);
void select_files(sInfo* info);
void manual(sInfo* info);
void recursive_unlink(string path);
bool is_protected_entry(char* name);
string resolve_item_path(sInfo* info, char* item);
string deletable_selected_files(sInfo* info);
void handmade_delete_file(string path, sInfo* info=info);
void handmade_selected_delete_file(sInfo* info);
void input(sInfo* info);

#endif
